/*
 *
 * AssignHealthCareServiceToLocationPage constants
 *
 */

/**
 *  AssignHealthCareServiceToLocationPage action types
 *  @type {string}
 */
export const DEFAULT_ACTION = 'ocpui/AssignHealthCareServiceToLocationPage/DEFAULT_ACTION';
export const INITIALIZE_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT = 'ocpui/HealthCareServices/INITIALIZE_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT';
export const GET_PAGED_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT = 'ocpui/HealthCareServices/GET_PAGED_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT';
export const GET_ACTIVE_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT = 'ocpui/HealthCareServices/GET_ACTIVE_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT';

export const GET_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT_SUCCESS = 'ocpui/HealthCareServices/GET_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT_SUCCESS';
export const GET_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT_ERROR = 'ocpui/HealthCareServices/GET_HEALTHCARE_SERVICES_LOCATION_ASSIGNMENT_ERROR';

/**
*  Other constants
*
*/
